/* ATools shortcuts */
Common
{
	NewFile			= Ctrl+N
	OpenFile		= Ctrl+O
	CloseFile		= Ctrl+F
	SaveFile		= Ctrl+S
	SaveFileAs		= Ctrl+Alt+S
	ExitApp			= Ctrl+Q
	Fullscreen		= F11
	About			= F1
	Copy			= Ctrl+C
	Cut				= Ctrl+X
	Paste			= Ctrl+V
	PlayPause		= Space
	ShowGrid		= Ctrl+G
	Undo			= Ctrl+Z
	Redo			= Ctrl+Y
}
WorldEditor
{
	// Object edition
	AddObj			= P
	DeleteObj		= Del
	DeleteAllObj	= Ctrl+Del
	SelectObj		=
	MoveObj			= M
	RotateObj		= R
	ScaleObj		= S
	HideObj			= Ctrl+H
	HideObjUpstair	= Ctrl+U
	ShowObj			= Ctrl+Alt+H
	LockSelection	= Space
	DialogTranslate	= Ctrl+T
	DialogRotate	= Ctrl+R
	DialogScale		= Ctrl+Shift+S
	RandomRotScale	= Ctrl+Alt+R
	Gravity			= Ctrl+G
	SetOnLand		= O
	UseGrid			= G
	// Camera edition
	MoveCamera		=
	RotateCamera	=
	ZoomCamera		=
	// Terrain edition
	EditHeight		= H
	EditTexture		= T
	EditColor		= C
	EditWater		= A
	ContinentVertex	= V
	// View
	TopView			= B
	SideView		= N
	Animate			= Ctrl+A
	// Axis
	AxisX			= X
	AxisY			= Y
	AxisZ			= Z
	AxisXZ			= W
	// Misc.
	WorldProperties	= Ctrl+P
	EditContinents	= Ctrl+W
	GenerateMinimap	= Ctrl+M
}
GUIEditor
{
	NewWindow		= Ctrl+N
	DeleteCtrl		= Del
	AlignTop		= T
	AlignLeft		= L
	AlignRight		= R
	AlignBottom		= B
	Cling			= C
	X				= X
	BringToFront	= F
}
ModelEditor
{
	ImportScale		= Ctrl+Alt+S
	EditEffects		= Ctrl+E
	ATEX			= Ctrl+T
}
ResEditor
{
	AddFiles		= Ctrl+A
	DeleteFiles		= Del
	ExtractFiles	= Ctrl+E
	ClientExtractor	= Ctrl+Alt+E
}
SfxEditor
{
	AddPart			= Ctrl+N
	DeletePart		= Del
	MergeFiles		= Ctrl+M
}